//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int IdCar { get; set; }
        public string Targa { get; set; }
        public string Modello { get; set; }
        public int PersonIdPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
