//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_fw_Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veicolo
    {
        public int IDVeicolo { get; set; }
        public string Targa { get; set; }
        public string Marca { get; set; }
        public string Modello { get; set; }
        public Nullable<int> IDProprietario { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
