//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_fw_Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemTransactions
    {
        public int StockItemTransactionID { get; set; }
        public int StockItemID { get; set; }
        public int TransactionTypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public System.DateTime TransactionOccurredWhen { get; set; }
        public decimal Quantity { get; set; }
        public int LastEditedBy { get; set; }
        public System.DateTime LastEditedWhen { get; set; }
    
        public virtual People People { get; set; }
        public virtual TransactionTypes TransactionTypes { get; set; }
        public virtual PurchaseOrders PurchaseOrders { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Invoices Invoices { get; set; }
        public virtual StockItems StockItems { get; set; }
    }
}
