USE [master]
GO
CREATE DATABASE [FootballDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FootballDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FootballDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FootballDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FootballDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [FootballDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FootballDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FootballDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FootballDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FootballDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FootballDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FootballDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FootballDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FootballDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FootballDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FootballDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FootballDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FootballDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FootballDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FootballDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FootballDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FootballDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FootballDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FootballDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FootballDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FootballDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FootballDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FootballDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [FootballDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FootballDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FootballDB] SET  MULTI_USER 
GO
ALTER DATABASE [FootballDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FootballDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FootballDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FootballDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FootballDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FootballDB] SET QUERY_STORE = OFF
GO
USE [FootballDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [FootballDB]
GO
/****** Object:  Table [dbo].[Giocatori]    Script Date: 07/10/2019 09:42:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Giocatori](
	[IdGiocatore] [int] IDENTITY(1,1) NOT NULL,
	[IdSquadra] [int] NULL,
	[Nome] [nvarchar](max) NULL,
	[Cognome] [nvarchar](max) NOT NULL,
	[Numero] [int] NOT NULL,
	[SquadraIdSquadra] [int] NULL,
 CONSTRAINT [PK_Giocatori] PRIMARY KEY CLUSTERED 
(
	[IdGiocatore] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Squadre]    Script Date: 07/10/2019 09:42:37 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Squadre](
	[IdSquadra] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Squadre] PRIMARY KEY CLUSTERED 
(
	[IdSquadra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Giocatori_SquadraIdSquadra]    Script Date: 07/10/2019 09:42:37 ******/
CREATE NONCLUSTERED INDEX [IX_Giocatori_SquadraIdSquadra] ON [dbo].[Giocatori]
(
	[SquadraIdSquadra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Giocatori]  WITH CHECK ADD  CONSTRAINT [FK_Giocatori_Squadre_SquadraIdSquadra] FOREIGN KEY([SquadraIdSquadra])
REFERENCES [dbo].[Squadre] ([IdSquadra])
GO
ALTER TABLE [dbo].[Giocatori] CHECK CONSTRAINT [FK_Giocatori_Squadre_SquadraIdSquadra]
GO
USE [master]
GO
ALTER DATABASE [FootballDB] SET  READ_WRITE 
GO
